services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: bobthebuilder
      POSTGRES_PASSWORD: afterlike
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: loona
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
